extends Node2D

var txt = "MOVA OS QUADRADOS AMARELOS DE FORMA QUE A SOMA DAS LINHAS, COLUNAS E DIAGOANAIS CORREPONDAM AOS VALORES FIXOS EM AZUL TRANFORMANDO OS QUADRADOS VERMELHOS EM VERDES. UM CLIQUE RETOMA O ESTADO ANTERIOR"


func _ready():
	get_node("Msg").set_text(txt)
	pass
